require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
permissions_path = '../node_modules/react-native-permissions/ios'
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
pod 'react-native-maps', path: '../node_modules/react-native-maps'
pod 'GoogleMaps' 
pod 'Google-Maps-iOS-Utils'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"





platform :ios, '11.0'


target 'nomadnote_rn' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-video', :path => '../node_modules/react-native-video'
  pod 'LineSDKSwift', '~> 5.0'

  pod 'FacebookSDK' 
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit' 
  pod 'FBSDKMessengerShareKit'
 
  pod 'FBSDKLoginKit'




  pod 'RCTYouTube', :path => '../node_modules/react-native-youtube'

  pod 'YouTubeSdk', :path => '../node_modules/react-native-youtube-sdk'

  pod 'RNSmtpMailer', :path => '../node_modules/react-native-smtp-mailer'

  target 'nomadnote_rnTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  post_install do |installer|
    # flipper_post_install(installer)
  end
end

target 'nomadnote_rn-tvOS' do
  # Pods for nomadnote_rn-tvOS

  target 'nomadnote_rn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end